### ISSUE TITLE
all examples for Creative board fail

### ISSUE THREAD

**Issue by AnttiLukats** [RISCV-on-Microsemi-FPGA/Hardware-Platforms#2]
please update!

**Comment by nitindeshpande** [comment]
Hello Antii,
The designs at this link https://github.com/RISCV-on-Microsemi-FPGA/Hardware-Platforms/tree/master/RISC-V-Creative-Board are designed to work with the Creative board with IGLOO2 mounted on it.

Could you please let us know which device if mounted on your creative board and what is the failure?

Regards,
Nitin, @CLappin

**Comment by CLappin** [comment]
Hi Antii, 

When using the SmartFusion2 Creative board, did you uncomment the `define in coreriscv_axi4_defines.v?
This converts all the larger memories into registers. This is usually used on the CoreRISCV_AXI4 on our smaller devices. In the later MiV cores this is not needed.

With regards to the CortexM1, it is used to set up the DDR and ENVM as well as other components. Once this is done it then goes into a  WFI loop until the next time the board is reset. It is also important to note that the M3 disable hex file starts at address 0x3C000 with "use as ROM" selected. The RISCV_BOOT sector can start from 0x00000. 

The M3-Disable_M2S025-FutureCreativeBoard-DDR.hex file found in the hex folder in the example project linked below. It can be used for most if not all designs for the creative except for PCIe which i think is not included in this hex file. [M3 Disable](https://github.com/RISCV-on-Microsemi-FPGA/M2S025-Creative-Board/tree/master/Modify_The_FPGA_Design/MIV_RV32IMA_L1_AHB_BaseDesign/hex)

In all of the MiV designs we have cached memory at 0x8000_0000 and un-cached memory and IOs at 0x6000_0000. New MiV_RV32IMA_L1_AHB base design for the M2S025 Creative Board is located [here](https://github.com/RISCV-on-Microsemi-FPGA/M2S025-Creative-Board). 

Thanks, 
Ciaran

**Comment by CLappin** [comment]
Hi Antti, 

Updates have been made to all repositories. 
Please reopen this issue if needed.

Thanks,
Ciaran
